# -*- coding: utf-8 -*-
"""restaurant_recom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_KZ3Zn73bwmHZ4fPVJyNFdpIdQSMmF9
"""

import csv
import pandas as pd
import numpy as np

data = pd.read_csv("app/pydata/2023-07-12_맛집.csv")
data.head()

df = pd.DataFrame(data)
del df['네이버 고유 아이디']
del df['시도']
del df['읍면동']

data['블로그카페리뷰수'].sort_values()

data['블로그카페리뷰수'].sort_values(ascending = False)
data.sort_values(by=['블로그카페리뷰수'])

print(df.head())

data['블로그카페리뷰수'].sort_values(ascending = False)
data.sort_values(by=['블로그카페리뷰수'])

grouped = df.groupby('군구')
grouped.first()

df.sort_values(by=["군구", "방문자총리뷰개수"], ascending=[True, False])
func = lambda g : g.sort_values(by='군구', ascending=False)[:3]
grouped.apply(func)

func = lambda g : g.sort_values(by='군구', ascending=False)[:3]
grouped.apply(func)

